FORMAT: 1A

# Polls

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/api]

### List All Questions [GET]

+ Response 200 (application/json)

        {
            "question": "Favourite programming language?",
        }